### ISSUE TITLE
In Chromium, Login doesn't work

### ISSUE THREAD

**Issue by ice09** [Steven-Ireland/ethmail.tech#1]
A file "portal" is downloaded. Using MetaMask in current version of Chromium (55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit))

**Comment by Steven-Ireland** [comment]
Try http://ethmail.tech/portal.html

I will fix the href link later tonight - Thanks so much!
Update - I need to redeploy the testnet contract as well, it seems embark has lost it :)

**Comment by ice09** [comment]
ok, that works. I tried to mail from one account to another one, both in MetaMask, but I cannot login again with my private key (there is just an empty main page). Will open another issue.
