### ISSUE TITLE
Im Chromium, after login with private key, empty main screen appears

### ISSUE THREAD

**Issue by ice09** [Steven-Ireland/ethmail.tech#2]
I tried to mail from one account to another one, both in MetaMask, but I cannot login again with my private key (there is just an empty main page). The file is correctly read it (shows in textbox), but after typing passphrase and clocking login, an empty main screen appears.

Seems to work though when I leave passphrase blank.

Could retry if the current addresses get resetted - is this possible? I can paste the addresses here, no problem since it's testnet.

**Comment by Steven-Ireland** [comment]
Should be fixed after 13ce45788b49613e52d960e8ae1ec6328d5bee1a. This was just a JS change so you can try again with your existing credentials.

**Comment by ice09** [comment]
great, works now, thx!

BTW have you heard of this peoject: https://github.com/monkeyscage/PERFECT-EMPTY-DAPP
I like the idea a lot, but the template is actually quite basic. I think your app could be a great sample for this as well, you use vue.js, right?
