### ISSUE TITLE
How are you hosting this?

### ISSUE THREAD

**Issue by vincentracine** [Steven-Ireland/ethmail.tech#4]
@Steven-Ireland This is really cool stuff! I'm just getting my head around all this dapp development life cycle. One thing I can't seem to understand is how are you hosting this application?

**Comment by Steven-Ireland** [comment]
Currently it's being hosted by surge. I'm in the middle of hosting the page on netlify (which will also integrate with github and auto-deploy new code). Once I have a version I'm very happy with (and when it is more mature) it will probably also be uploaded to swarm.

The nice part about developing Dapps is the blockchain is your backend! No need to dedicate a whole server to it when there's plenty of free static hosting available.
